<?xml version="1.0"?>
<robot name="mybot"
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Gazebo 설정 파일 포함 -->
  <xacro:include filename="$(find mybot_description)/urdf/mybot.gazebo.xacro"/>

  <!-- Properties (변수) 정의 -->
  <xacro:property name="base_width" value="0.38"/>
  <xacro:property name="base_length" value="0.925"/>
  <xacro:property name="base_height" value="0.21"/>

  <xacro:property name="wheel_radius" value="0.16459"/>
  <xacro:property name="wheel_length" value="0.11653"/>
  <xacro:property name="wheel_mass" value="8"/>

  <xacro:property name="wheel_offset_x" value="0.249"/>
  <xacro:property name="wheel_offset_y" value="0.29153"/>
  <xacro:property name="wheel_offset_z" value="-0.0702"/>

  <xacro:property name="camera_size" value="0.02"/>
  <xacro:property name="lidar_radius" value="0.03"/>
  <xacro:property name="lidar_length" value="0.1"/>

  <!-- 계산된 속성 -->
  <xacro:property name="wheel_separation" value="${wheel_offset_y * 2}"/>

  <!-- 재질 정의 -->
  <material name="red">
    <color rgba="1.0 0.0 0.0 1.0"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <!-- 바퀴 매크로 정의 -->
  <xacro:macro name="wheel" params="prefix pos_x pos_y pos_z flip wheel_type *origin *axis">
    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <mesh filename="package://mybot_description/meshes/${wheel_type}.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="1.570795 0 0"/>
        <geometry>
          <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia ixx="0.1171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.1171"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <xacro:insert_block name="origin"/>
      <xacro:insert_block name="axis"/>
      <dynamics damping="0.0" friction="20"/>
    </joint>

    <!-- Gazebo 속성 적용 -->
    <xacro:wheel_gazebo prefix="${prefix}"/>
  </xacro:macro>

  <!-- Base footprint link -->
  <link name="base_footprint"/>
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0.2352" rpy="0 0 0"/>
  </joint>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://mybot_description/meshes/base_link.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.008"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <collision>
      <origin xyz="0 0 0.035"/>
      <geometry>
        <box size="0.154 0.627 0.07"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="50"/>
      <origin xyz="0.0 0.0 0.0"/>
      <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465"/>
    </inertial>
  </link>

  <!-- Camera link -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.000083" ixy="0" ixz="0" iyy="0.000083" iyz="0" izz="0.000083"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.40 0.0 0.04"/>
  </joint>

  <!-- 2D LiDAR Link -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.000045" ixy="0" ixz="0" iyy="0.000045" iyz="0" izz="0.000075"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 0.13" rpy="0 0 0"/>
  </joint>

  <!-- 바퀴 생성 -->
  <xacro:wheel prefix="front_right" pos_x="${wheel_offset_x}" pos_y="${-wheel_offset_y}" pos_z="${wheel_offset_z}" flip="true" wheel_type="wheel_type1">
    <origin rpy="3.14 0 0" xyz="${wheel_offset_x} ${-wheel_offset_y} ${wheel_offset_z}"/>
    <axis xyz="0 -1 0"/>
  </xacro:wheel>

  <xacro:wheel prefix="front_left" pos_x="${wheel_offset_x}" pos_y="${wheel_offset_y}" pos_z="${wheel_offset_z}" flip="false" wheel_type="wheel_type2">
    <origin rpy="0 0 0" xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}"/>
    <axis xyz="0 1 0"/>
  </xacro:wheel>

  <xacro:wheel prefix="rear_left" pos_x="${-wheel_offset_x}" pos_y="${wheel_offset_y}" pos_z="${wheel_offset_z}" flip="false" wheel_type="wheel_type2">
    <origin rpy="0 0 0" xyz="${-wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}"/>
    <axis xyz="0 1 0"/>
  </xacro:wheel>

  <xacro:wheel prefix="rear_right" pos_x="${-wheel_offset_x}" pos_y="${-wheel_offset_y}" pos_z="${wheel_offset_z}" flip="true" wheel_type="wheel_type1">
    <origin rpy="3.14 0 0" xyz="${-wheel_offset_x} ${-wheel_offset_y} ${wheel_offset_z}"/>
    <axis xyz="0 -1 0"/>
  </xacro:wheel>

</robot>